### ISSUE TITLE
Bodydetails endpoint for python

### ISSUE THREAD

**Issue by hughgoodbody** [onshape-public/onshape-clients#10]
As discussed, request for a bodydetails endpoint for python

**Comment by ethan92429** [comment]
This is here: https://github.com/onshape-public/onshape-clients/blob/master/python/onshape_client/oas/api/part_studios_api.py#L1500

**Comment by ethan92429** [comment]
Note that you'll have to use _preload_content=False to actually get the data because the response from this endpoint isn't typed yet.
