### ISSUE TITLE
onshape-client-0.0.37 on pypi does not install correctly

### ISSUE THREAD

**Issue by pmdhazy** [onshape-public/onshape-clients#19]
Not sure if this is the right place for this bug report but if I do:

pip install --upgrade onshape-client==0.0.37
it does not install correctly and a simple "import onshape_client" does not work.

> 
> Python 3.6.6 (default, Jul 19 2018, 14:25:17)
> [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)] on linux
> Type "help", "copyright", "credits" or "license" for more information
> >>> import onshape_client
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'onshape_client'
> 

Doing pip install --upgrade onshape-client==0.0.35
does work.

Version 37 seems to install to .../env3/lib/python3.6/site-packages/python/ rather than
.../env3/lib/python3.6/site-packages/onshape_client

**Comment by ethan92429** [comment]
Hi @pmdhazy 

Please try version 1.1.0: https://pypi.org/project/onshape-client/#history .

**Comment by pmdhazy** [comment]
Hi @ethan92429 ,

It install OK now so this issue is fixed but I now get errors when using it. Not yet had time to find out why but for example:

>  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 62, in set_attribute
>     "{0} has no key '{1}'".format(type(self).__name__, name), path_to_item
> onshape_client.oas.exceptions.ApiKeyError: "BTGlobalTreeNodeInfo has no key 'canUnshare' at ['received_data']['items'][0]['canUnshare']"

This was from the following code:

` results = client.documents_api.get_documents(
                  owner=company_id,
                  q=name,
                  filter=7,  # company docs only
                  )
 `

**Comment by ethan92429** [comment]
This should be fixed.
