### ISSUE TITLE
python TranslationsApi.get_translation returns None

### ISSUE THREAD

**Issue by Evoiis** [onshape-public/onshape-clients#8]
Shouldn't this api call return a dictionary similar to the Get Translation Status call in the API Explorer?

Source:
https://github.com/onshape-public/onshape-clients/blob/master/python/docs/TranslationsApi.md#get_translation

**Comment by Evoiis** [comment]
The calls are actually all setup. 
Because in `get_translation_with_http_info` in translations_api.py the response_type is None.

When in api_client.call_api it returns None instead of `response_data` which is the proper return for this api call.

**Comment by ethan92429** [comment]
Fixed.
